MetaMask/eth-snap-keyring

jest.config.js, src/snap-keyring.test.ts, src/snap-keyring.ts, src/types.ts
This function will be called by the snap controller instead of the
bridge.
=> refactor: remove `saveSnapKeyring` argument from `handleKeyringSnapMessage`

jest.config.js, package.json, src/snap-keyring.test.ts, src/snap-keyring.ts, src/util.test.ts, yarn.lock
When a snap calls the `'read'` method, the main use case is to allow the snap to detect any synchronization problems between it and the bridge.
This PR makes sure that we return the accounts from the bridge's state instead of calling back the snap.
=> fix: fix circular read when handling `'read'` requests

src/snap-keyring.test.ts, src/snap-keyring.ts, src/types.ts
PR to support changes requested at <https://github.com/MetaMask/snaps/pull/1290>.
=> feat: use objects in snap -> controller methods

jest.config.js, src/snap-keyring.ts, yarn.lock
The syncronization is already done once the snap notifies the keyring controller.
=> chore: don't sync accounts twice on deletion

src/snap-keyring.ts
Otherwise the removal from maps is going to be scheduled and not awaited by the `KeyringController`.
=> fix: remove account from maps first

jest.config.js, src/SnapKeyring.test.ts, src/SnapKeyring.ts
This PR fixes a leak in the deferred promises when the call to `submitRequest()` throws an exception.
=> fix: remove promise if `submitRequest()` throws

src/SnapKeyring.test.ts, src/SnapKeyring.ts, src/util.ts
This PR adds a `removeAccount` callback to the `SnapKeyring` that will be called when the snap notify us that it deleted an account.
=> feat: add `removeAccount` callback to constructor

package.json, yarn.lock
Trying to align our `@metamask/providers` version in extension. Need to bump `@metamask/keyring-api` to 0.2.5 where [providers is bumped to 13.0.0](https://github.com/MetaMask/keyring-api/compare/v0.2.4...v0.2.5#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519)
* See: https://github.com/MetaMask/metamask-extension/pull/20917
=> bump @metamask/keyring-api to v0.2.5

src/SnapKeyring.test.ts, src/SnapKeyring.ts
This PR is a refactor of how the account management methods are handled. Instead of simply syncing all the snap accounts everytime an account is added, removed, or updated, the keyring will handle each one of the event individually.
The keyring state is also updated to store the snap ID next to the account object, and thus making them closer tied.
=> refactor: handle account management methods instead of syncing accounts

src/SnapKeyring.test.ts, src/SnapKeyring.ts
The `removeAccountsBySnapId` method will be used by the UI to remove all accounts related to a snap.
=> feat: add method to remove all accounts given a snap ID

src/SnapKeyring.test.ts, src/SnapKeyring.ts
works alongside this PR in the extension: https://github.com/MetaMask/metamask-extension/pull/20684
follow steps outlined in the linked extension PR to test
=> feat: handle approval when adding/removing account

src/SnapKeyring.test.ts, src/SnapKeyring.ts
Accounts shouldn't be removed by directly calling the keyring because they also need to be removed from other controllers, which is done by the `removeAccount` method from `metamask-controller.js`.
=> fix: remove the `removeAccountsBySnapId` method

src/SnapKeyring.test.ts, src/SnapKeyring.ts
This method will be used by the UI to get the addresses of the accounts to be removed.
=> feat: add the `getAccountsBySnapId` method

.github/workflows/build-lint-test.yml, CHANGELOG.md
This PR adds the `--prettier` option to the auto-changelog commands to format the changelog file.
=> chore: use `--prettier` option of auto-changelog

src/SnapKeyring.test.ts, src/SnapKeyring.ts
This method should be removed in the future once we have the Accounts Controller, but for now we have to rely on exposing this method to allow other components to get the Snap metadata associated with an account.
=> feat: add `getAccountByAddress` method

yarn.lock
These dependencies were reported as vulnerable.
=> chore(deps): bump `word-wrap` and `semver`

src/SnapKeyring.test.ts, src/SnapKeyring.ts
This PR enables this issue: https://github.com/MetaMask/accounts-planning/issues/35
This callback will be implemented in [this extension PR](https://github.com/MetaMask/metamask-extension/pull/21218). 
For async transactions, we call this callback which will trigger a confirmation modal in the extension with the URL and the message as part of the UI. This will be used to instruct users to complete signings at the specified URL or app. 
- add a `redirectUser` callback with the following structure
```ts
redirectUser(
snapId: string,
url: string,
message: string,
method: string,
): Promise<void>;
```
- inside `submitRequest`, add the following block 
```ts
if (response.redirect?.message || response.redirect?.url) {
const { message = '', url = '' } = response.redirect;
await …
```
=> feat: add `redirectUser` callback

src/SnapKeyring.test.ts, src/SnapKeyring.ts
This Pr removes the async prefix for the functions `listAccounts` and `getAccountByAddress`.
=> fix: remove `async` from `listAccounts` and `getAccountByAddress`

package.json, yarn.lock
- Update dependency `@metamask/keyring-api` from `^1.0.0` to `^1.1.0`
- [CHANGELOG](https://github.com/MetaMask/keyring-api/blob/main/CHANGELOG.md)
- [diff](https://github.com/MetaMask/keyring-api/compare/v1.0.0...v1.1.0) 
- Bump `@metamask/snaps-controllers` from `^3.0.0` to `^3.1.0` to align with transitive
=> deps: @metamask/keyring-api@^1.0.0->^1.1.0

src/SnapIdMap.test.ts, src/SnapIdMap.ts, src/SnapKeyring.test.ts, src/SnapKeyring.ts
The `SnapIdMap` requires a `snapId` value to be passed to the `get`, `has`, and `delete` methods. Its goal is to ensure that the correct Snap ID must be passed, thus preventing a Snap from accessing or deleting a value from another Snap.
=> feat: use a `snapId`-indexed map

package.json, src/KeyringSnapControllerClient.test.ts, src/KeyringSnapControllerClient.ts, src/SnapKeyring.ts, yarn.lock
This PR adds the `KeyringSnapControllerClient` to this package since it's being removed from the `keyring-api`.
See: <https://github.com/MetaMask/keyring-api/pull/241>
=> feat: add `KeyringSnapControllerClient` class

src/SnapKeyring.test.ts, src/SnapKeyring.ts, src/caip.test.ts, src/caip.ts
This is the first step of adding a CAIP-2 scope to internal requests.
It's a "first step" as for now, we cannot get/extract the `chainId` for some methods. This would require a much bigger refactor (which will come later).
The `chainId` is part of the transaction request, so we extract it from there and attach it to the internal request.
The `chainId` is part of the `domain` field (as defined by EIP-712), however, some older versions of the `eth_signTypedData_vX` might not have it! In this case, we do not provide the `scope`.
As of today, only those methods do not have the `domain`:
- `eth_signTypedData`
- `eth_signTypedData_v1`
- Partially fixes: [MetaMask/accounts-planning#272](https://github.com/MetaMask/accounts-planning/issues/272)
1. Use the …
=> feat(272): add `chainId` to Keyring API requests (transaction/typed message)

package.json, yarn.lock
This pull request updates the dependencies in the project. Specifically, it updates the versions of the following packages:
- `@metamask/keyring-api`: from 4.0.0 to 4.0.1
- `@metamask/snaps-controllers`: from 5.0.1 to 6.0.2
- `@metamask/snaps-sdk`: from 2.1.0 to 3.1.0
- `@metamask/snaps-utils`: from 6.1.0 to 7.0.2
These updates ensure that the project is using the latest versions of these packages, which may include bug fixes, performance improvements, and new features.
=> chore(deps): bump @metamask dependencies

src/SnapKeyring.test.ts, src/SnapKeyring.ts
This pull request adds tests for the `prepareUserOperation` and `patchUserOperation` methods in the `SnapKeyring` class. The tests ensure that the methods correctly handle requests to the Snap and handle pending responses.
Resolves: metamask/accounts-planning#290
=> fix: enforce that responses of `prepareUserOperation` and `patchUserOperation` are synchronous

src/SnapKeyring.ts, src/logger.ts
This uses the same logging mechanism than the extension (using `@metamask/utils` logging).
You can configure the logger using the `DEBUG` "env variable" from your `.metamaskrc`. Every MetaMask logs are prefixed by `metamask:`.
In our case, the log prefix would be: `metamask:eth-snap-keyring`.
Add this resolution to your extension's `package.json`:
```json
...
"resolutions": {
"@metamask/eth-snap-keyring@^2.2.0": "metamask/eth-snap-keyring#fb923891d9497ad4b207191699e79f364aad74ce",
},
... 
```
> You might need more version resolutions depending on your dependency, you can check them with `yarn why @metamask/eth-snap-keyring`
Then, run some actions (using the e2e dapp for example) and check logs of your extension (see the screenshots for an example).
For now we do log every Snap requests …
=> feat: add logger + now log Snap requests

package.json, yarn.lock
Bump `@metamask/keyring-api` from 5.0.0 to 5.1.0.
=> chore(deps): bump @metamask/keyring-api from 5.0.0 to 5.1.0

package.json, yarn.lock
Even though this bump might not seems necessary, it emphasis the fact that we do now require the `8.4.0` of `@metamask/utils` that provides the new CAIP helpers.
=> chore(deps): bump @metamask/utils from 8.3.0 to 8.4.0

package.json, src/SnapKeyring.test.ts, src/SnapKeyring.ts, yarn.lock
This pull request updates the @metamask/keyring-api dependency to version 6.0.0. It also includes a chore commit to bump the keyring-api version.
=> chore(deps): update @metamask/keyring-api to version 6.0.0

package.json, src/SnapKeyring.test.ts, src/SnapKeyring.ts, yarn.lock
This pull request updates the @metamask/keyring-api dependency to version 6.1.0 and fixes tests.
=> Bump @metamask/keyring-api to version 6.1.0 and fix tests

package.json, src/SnapKeyring.test.ts, src/SnapKeyring.ts, yarn.lock
There was a breaking change in 6.3 that merges the EthMethod and Eth4337Methods. This pr fixes this.
=> fix: 4337 methods from keyring-api 6.2.1

.github/dependabot.yml
This PR modifies the Dependabot configuration to group together updates for all Snaps dependencies. It also changes the `versioning-strategy` to `increase`.
=> ci: group Snaps dependencies updates

package.json, yarn.lock
I accidentally added this as a dependency in #389.
=> Remove `@metamask/snaps-execution-environments` dependency
